name: training_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  i18n: ^4.1.0
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/male_body/front/
    - assets/svg/male_body/back/
